---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "35"
year: "2019"
contributor: 
- "Ben Kaden"
title: "Ein Nachruf auf Professor Walther Umstätter"
subtitle: "(* 12. Juni 1941 in Ploiești, Königreich Rumänien; † 6. März 2019 in Altlandsberg)"
pdf: master.pdf
date: 2019-04-20
comments: false
sharing: true
footer: true

---