---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "35"
year: "2019"
contributor: 
- "Karsten Schuldt"
title: "Neutralität als bürgerliche Bibliotheksideologie. Die Kritik der <q>Arbeiterbibliotheken</q> zu Beginn des 20. Jahrhunderts"
urn: "urn:nbn:de:kobv:11-110-18452/21092-2"
date: 2019-04-01
comments: false
sharing: true
footer: true

---