---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "35"
year: "2019"
contributor: 
- "Karsten Schuldt"
title: "Neutralität als bürgerliche Bibliotheksideologie. Die Kritik der <q>Arbeiterbibliotheken</q> zu Beginn des 20. Jahrhunderts"
pdf: master.pdf
date: 2019-04-01
comments: false
sharing: true
footer: true

---