---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "35"
year: "2019"
contributor: 
- "Redaktion LIBREAS"
title: "Editorial #35: Neutralität. Bibliotheken zwischen Pluralität und Propaganda"
urn: "urn:nbn:de:kobv:11-110-18452/21096-6"
date: 2019-04-14
comments: false
sharing: true
footer: true

---