---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "35"
year: "2019"
contributor: 
- "Redaktion LIBREAS"
title: "Editorial #35: Neutralität. Bibliotheken zwischen Pluralität und Propaganda"
pdf: master.pdf
date: 2019-04-14
comments: false
sharing: true
footer: true

---