---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "35"
year: "2019"
contributor: 
- "Michaela Voigt"
- "Sebastian Dittmann"
title: "Zweitveröffentlichungsservice der TU Berlin – Automatisierungsmöglichkeiten für den Workflow"
pdf: master.pdf
abstract: "Der Artikel stellt den mithilfe von OpenRefine teilautomatisierten Workflow des Zweitveröffentlichungsservices der Technischen Universität Berlin vor: Es werden Hintergründe und Abwägungen, die einzelnen Schritte im Workflow und Möglichkeiten zur Nachnutzung der erarbeiteten Materialien beschrieben und diskutiert."
date: 2019-04-01
comments: false
sharing: true
footer: true

---