---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "35"
year: "2019"
contributor: 
- "Sebastian Nordhoff"
title: "Warum kostet ein wissenschaftliches Buch 28.000 EUR?"
pdf: master.pdf
abstract: "Dieser Aufsatz bespricht die Kostenstruktur der Produktion von Open-Access-Büchern und weist auf den derzeitigen Mangel an belastbaren Zahlen zu den tatsächlichen Kosten der OA-Buchproduktion hin. Um diesem Mangel abzuhelfen, wird eine gemeinschaftliche Anstrengung zur offenen Inventarisierung und Bepreisung der erfordelichen Tätigkeiten gefordert. Eine Referenzimplementierung wird anhand des Projekts  <q>Full disclosure: replicable strategies for book publications supplemented with empirical data</q> vorgestellt."
date: 2019-04-20
comments: false
sharing: true
footer: true

---