---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "35"
year: "2019"
contributor: 
- "Redaktion LIBREAS"
title: "Das liest die LIBREAS, Nummer #4 (Winter 2018-Frühling 2019)"
urn: "urn:nbn:de:kobv:11-110-18452/21086-6"
date: 2019-04-21
comments: false
sharing: true
footer: true

---