---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "35"
year: "2019"
contributor: 
- "Redaktion LIBREAS"
title: "Das liest die LIBREAS, Nummer #4 (Winter 2018-Frühling 2019)"
pdf: "master-pdf"
date: 2019-04-21
comments: false
sharing: true
footer: true

---