---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "35"
year: "2019"
contributor: 
- "Redaktion LIBREAS"
title: "Erinnerung an Uwe Müller"
date: 2019-04-21
comments: false
sharing: true
footer: true

---