---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "35"
year: "2019"
contributor: 
- "Ben Kaden"
- "Michael Kleineberg"
title: "Scholarly Makerspaces – Ein Zwischenbericht zum DFG-Projekt FuReSH"
urn: "urn:nbn:de:kobv:11-110-18452/21088-8"
date: 2019-04-25
comments: false
sharing: true
footer: true

---