---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "35"
year: "2019"
contributor: 
- "Ben Kaden"
- "Michael Kleineberg"
title: "Scholarly Makerspaces – Ein Zwischenbericht zum DFG-Projekt FuReSH"
pdf: master.pdf
date: 2019-04-25
comments: false
sharing: true
footer: true

---