---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "35"
year: "2019"
contributor: 
- "Christian Meskó"
title: "Die Torwächter des öffentlichen Wissens"
subtitle: "Politischer Positionsbezug gegen rechts von Öffentlichen Bibliotheken in Deutschland"
pdf: master.pdf
abstract: "Gegenwärtig erlebt der Rückbezug auf vermeintlich bedrohte nationale und kulturelle Identitäten weltweit einen Aufschwung. Ursachen dafür
werden oft in den, durch zahlreiche Kriegs- und Konfliktherde
ausgelösten, Bewegungen von Flüchtlingen ausgemacht, die es in das
Zentrum kapitalistischer Wohlfahrtsstaaten zieht. Die
Instrumentalisierung von Abstiegsängsten bei den Mittel- und
Unterschichten betroffener Länder, wird aber nicht nur auf den digitalen
Plattformen sozialer Medien betrieben, sondern auch auf den etablierten
Podien und in den traditionellen Institutionen öffentlicher
Wissensvermittlung. Die rechtsnationalen bis rechtsradikalen Stimmen
inszenieren sich gegenwärtig oft als Opfer, weil sie angeblich nicht
mehr gehört würden. Sie empören sich in diesem Zusammenhang, weil Sie
eine angebliche Mehrheitsmeinung aussprechen, die vermeintlich lange
genug durch liberale Wortkosmetik tabuisiert wurde. Durch immer
professionellere Medienstrategien haben sie aber längst erreicht, dass
ihre Stimmen im Gegenteil unverhältnismäßig oft gehört und medial
verbreitet werden. Zu den Bühnen, die sie wählen, gehören Zeitungen,
soziale Netzwerke, Talkshows, Podiumsdiskussionen und Demonstrationen
ebenso, wie etwa die Bestände von Buchhandlungen und Bibliotheken. Im
Spannungsfeld von Neutralität, Informationsfreiheit und den
Schutzrechten diskriminierter Minderheiten, stellt sich auch dem
Fachpersonal öffentlicher Bibliotheken die Frage, wie sie die
Öffentlichkeit darin unterstützen kann, die Debatten nicht von
Rechtsnationalen und Rechtsextremen vereinnahmen zu lassen. Ohne Zensur
auszuüben oder für bestimmte Gruppen Partei zu ergreifen, hat das
Fachpersonal von öffentlichen Bibliotheken die schwierige
Herausforderung zu bewältigen, darauf eine Antwort zu finden."
date: 2019-04-01
comments: false
sharing: true
footer: true

---
