---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "35"
year: "2019"
contributor: 
- "Irmela Roschmann-Steltenkamp"
title: "Neutralität in Bibliotheken – ein Werkstattbericht"
urn: "urn:nbn:de:kobv:11-110-18452/21095-0"
abstract: "Der Beitrag ist ein Werkstattbericht der Bibliothek des Zentrums für Antisemitismusforschung, deren regulärer Bestand zum Teil aus rechter Literatur besteht und der Umgang damit ein tagtäglicher ist. Nach einer kurzen Einführung entwickelt der Aufsatz anhand der Schritte Erwerbung, Katalogisierung sowie Standort – Zugänglichkeit – Nutzung den Arbeitsalltag mit rechter Literatur."
abstractalt: "The article is a workshop report of the library of the Center of Research on Antisemitism. The regular collection consists partly of right-wing literature. After a short introduction, the essay depicts the use of this literature on a daily basis along the steps <q>acquisition</q>, <q>cataloguing</q> and <q>location-accessibility</q>."
date: 2019-04-01
comments: false
sharing: true
footer: true

---