---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "35"
year: "2019"
contributor: 
- "Katharina Leyrer"
title: "Zur Unmöglichkeit eines neutralen Bibliotheksangebots"
urn: "urn:nbn:de:kobv:11-110-18452/21093-8"
date: 2019-04-21
comments: false
sharing: true
footer: true

---