---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "35"
year: "2019"
contributor: 
- "Katharina Leyrer"
title: "Zur Unmöglichkeit eines neutralen Bibliotheksangebots"
pdf: master.pdf
date: 2019-04-21
comments: false
sharing: true
footer: true

---