---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "35"
year: "2019"
contributor: 
- "Christian Koller"
title: "Weder Zensur noch Propaganda: Der Umgang des Schweizerischen Sozialarchivs mit rechtsextremem Material"
urn: "urn:nbn:de:kobv:11-110-18452/21094-4"
abstract: "Das Schweizerische Sozialarchiv hat eine lange Tradition der Sammlung rechtsextremen Materials. Der Artikel skizziert Umfang und Schwerpunkte dieser Sammlung und diskutiert Erwerbungsstrategien und Benutzungsbedingungen im Lichte der Frage, ob Bibliotheken solche Literatur <q>neutral</q> behandeln oder wegen politischer Kontaminationsgefahr aus ihren Beständen fernhalten sollen."
abstractalt: "The Swiss Social Archives have a long tradition of collecting far-right material. This article considers extent and contents of this collection and discusses acquisition strategies and terms of use in view of the question whether libraries ought to treat such material <q>neutrally</q> or should rather exclude them to prevent spreading anti-democratic ideas."
date: 2019-04-01
comments: false
sharing: true
footer: true

---